name: Android

# Step 1: Choose the branch or branches you want to run this workflow
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install firestore-emulator
        run: |
          pushd firestore-emulator
          npm install
          popd

      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

      # Step 2: Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > app/google-services.json

      # Step 3: Check the code with Android linter
      - name: Run Android Linter
        run: ./gradlew lint

      # Step 4: Run your unit tests
      - name: Set-up firestore emulator and run unit tests
        run: |
          pushd firestore-emulator
          npm run test -- --token "$FIREBASE_TOKEN"
          popd
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      # Upload test results as artifacts
      - name: Archive test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: app/build/reports/tests

      # Step 5: Assemble debug apk to send to firebase test lab
      - name: Assemble Debug APK
        run: ./gradlew assemble

      # Step 6: Assemble debug test apk to send to firebase test lab
      - name: Assemble Debug Test APK
        run: ./gradlew assembleAndroidTest

      # Step 7: Run instrumented tests on firebase test lab
      - name: Run tests on Firebase Test Lab
        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
        with:
          arg-spec: '.github/test-lab-config.yml:android-pixel-4'
        env:
          SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        continue-on-error: true
